''

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -10,8 +10,7 @@ commands:
           name: Destroy environments
           when: on_fail
           command: |
-            # Your code here
-            exit 1
+            aws cloudformation delete-stack --stack-name myStack-${CIRCLE_WORKFLOW_ID:0:7}
 
   revert-migrations:
     description: Revert the last migration if successfully run in the current workflow.
@@ -43,8 +42,9 @@ jobs:
       - run:
           name: Build front-end
           command: |
-            # Your code here
-            exit 1
+            name: npm run build
+            working_directory: ./frontend
+            command: npm run build
       - save_cache:
           paths: [frontend/node_modules]
           key: frontend-build
@@ -59,208 +59,306 @@ jobs:
       - run:
           name: Back-end build
           command: |
-             # Your code here
-             exit 1
+              name: npm run build
+              working_directory: ./backend
+              command: npm run build
       - save_cache:
           paths: [backend/node_modules]
           key: backend-build
 
-  test-frontend:
-    docker:
-      # Docker image here
-    steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
+#   test-frontend:
+#     docker:
+#       docker:
+#         - image: circleci/node:13.8.0
+#     steps:
+#       - checkout
+#       - run:
+#           name: Install junit coverage reporter
+#           working_directory: ./frontend
+#           command: npm install --save-dev jest-junit
+#       - run:
+#           name: Run tests with JUnit as reporter
+#           working_directory: ./frontend
+#           command: npm test -- --ci --runInBand --reporters=default --reporters=jest-junit && pwd && ls -la /tmp
+#           environment:
+#             JEST_JUNIT_OUTPUT_DIR: ./test_results
+#       - store_test_results:
+#           path: ./frontend/test_results
+#       - store_artifacts:
+#           path: ./frontend/test_results
                 
-  test-backend:
-    docker:
-      # Docker image here
-    steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
+#   test-backend:
+#     docker:
+#       docker:
+#         - image: circleci/node:13.8.0
+#     steps:
+#       - checkout
+#       - run:
+#           name: Install junit coverage reporter
+#           working_directory: ./backend
+#           command: npm install --save-dev jest-junit
+#       - run:
+#           name: Run tests with JUnit as reporter
+#           working_directory: ./backend
+#           command: npm test -- --ci --runInBand --reporters=default --reporters=jest-junit && pwd
+#           environment:
+#             JEST_JUNIT_OUTPUT_DIR: ./test_results
+#       - store_test_results:
+#           path: ./backend/test_results
+#       - store_artifacts:
+#           path: ./backend/test_results
             
-  scan-frontend:
-    docker:
-      # Docker image here
-    steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
+#   scan-frontend:
+#     docker:
+#       - image: circleci/node:13.8.0
+#     steps:
+#       - checkout
+#       - run:
+#           name: Check Frontend against security vulnerabilities
+#           working_directory: ./frontend
+#           command: npm audit --audit-level=critical
 
-  scan-backend:
-    docker:
-      # Docker image here
-    steps:
-      # Checkout code from git
-      # Restore from cache
-      # Your job code here
+#   scan-backend:
+#     docker:
+#       - image: circleci/node:13.8.0
+#     steps:
+#       - checkout
+#       - run:
+#           name: Check Backend against security vulnerabilities
+#           working_directory: ./backend
+#           command: npm audit --audit-level=critical
 
-  deploy-infrastructure:
-    docker:
-      # Docker image here that supports AWS CLI
-    steps:
-      # Checkout code from git
-      - run:
-          name: Ensure back-end infrastructure exists
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/backend.yml \
-              #--tags project=your-tag \
-              # --stack-name "your back-end stack name with workflow id" \
-              # --parameter-overrides ID="your workflow id"  
-              exit 1
-      - run:
-          name: Ensure front-end infrastructure exist
-          command: |
-            aws cloudformation deploy \
-              --template-file .circleci/files/frontend.yml \
-              #--tags project=your-tag \
-              # --stack-name "your front-end stack name with workflow id" \
-              # --parameter-overrides ID="your workflow id"  
-              exit 1
-      - run:
-          name: Add back-end ip to ansible inventory
-          command: |
-            # Your code here
-            exit 1
-      - persist_to_workspace:
-          root: ~/
-          paths:
-            - project/.circleci/ansible/inventory.txt
-      # Here's where you will add some code to rollback on failure      
+#   deploy-infrastructure:
+#     docker:
+#       - image: amazon/aws-cli
+#     steps:
+#       - checkout
+#       - run:
+#           name: Ensure back-end infrastructure exists
+#           command: |
+#             aws cloudformation deploy \
+#               --template-file .circleci/files/backend.yml \
+#               #--tags project=your-tag \
+#               # --stack-name "your back-end stack name with workflow id" \
+#               # --parameter-overrides ID="your workflow id"  
+#               exit 1
+#       - run:
+#           name: Ensure front-end infrastructure exist
+#           command: |
+#             aws cloudformation deploy \
+#               --template-file .circleci/files/frontend.yml \
+#               #--tags project=your-tag \
+#               # --stack-name "your front-end stack name with workflow id" \
+#               # --parameter-overrides ID="your workflow id"  
+#               exit 1
+#       - run:
+#           name: Add back-end ip to ansible inventory
+#           command: |
+#             echo [all] > inventory.txt
+#             aws ec2 describe-instances \
+#               --query 'Reservations[*].Instances[*].PublicIpAddress' \
+#               --filters "Name=tag:Project,Values=udacity" \
+#               --output text >> inventory.txt
+#             exit 1
+#       - persist_to_workspace:
+#           root: ~/
+#           paths:
+#             - project/.circleci/ansible/inventory.txt
+#       - destroy-environment      
 
-  configure-infrastructure:
-    docker:
-      # Docker image here that supports Ansible
-    steps:
-      # Checkout code from git
-      # Add ssh keys with fingerprint
-      # attach workspace
-      - run:
-          name: Install dependencies
-          command: |
-            # Your code here
-            exit 1
-      - run:
-          name: Configure server
-          command: |
-            # Your code here
-            exit 1
-      # Here's where you will add some code to rollback on failure      
+#   configure-infrastructure:
+#     docker:
+#       docker:
+#       - image: amazon/aws-cli
+#     steps:
+#       - checkout
+#       - add_ssh_keys:
+#           fingerprints: ["06:55:19:5c:75:9c:0c:fa:5e:f0:ed:c4:2b:35:ec:76"]
+#       - attach_workspace:
+#           at: .
+#       - run:
+#           name: Install dependencies
+#           working_directory: ./.circleci/ansible
+#           command: |
+#             apk add --update ansible
+#             ansible --version
+#       - run:
+#           name: Configure server
+#           working_directory: ./.circleci/ansible
+#           command: |
+#             pwd &&
+#             ls -la
+#             cat inventory
+#             ansible-playbook -i inventory configure-server.yaml
+#       - destroy_environment:
+#           id: ${CIRCLE_WORKFLOW_ID:0:7}
+#           when: on_fail
+#   run-migrations:
+#     docker:
+#       docker:
+#       - image: circleci/node:13.8.0
+#     steps:
+#       - checkout
+#       - attach_workspace:
+#           at: .
+#       - run:
+#           name: Install AWS CLI dependencies
+#           working_directory: /tmp
+#           command: |
+#             sudo apt-get update && sudo apt-get install -yy less
+#             curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+#             unzip awscliv2.zip
+#             sudo ./aws/install
+#       - run:
+#           name: Run migrations
+#           working_directory: ./backend
+#           command: |
+#             npm run migrations > migration_status
+#       - run:
+#           name: Send migration results to memstash
+#           working_directory: ./backend
+#           command: |
+#             if grep -q "has been executed successfully" migration_status
+#             then
+#               echo "DB migration was successful, will update memstash..."
+#               curl -H "Content-Type: text/plain" -H "token: 2a9e15d6-b9fa-4b1f-a5dc-e3b9643a9b63" --request PUT --data "success" https://api.memstash.io/values/DB_MIGRATION_${CIRCLE_WORKFLOW_ID:0:7}
+#             else
+#               echo "DB migration failed, please verify setup! Probably the database already exists. Verify setup!"
+#               curl -H "Content-Type: text/plain" -H "token: 2a9e15d6-b9fa-4b1f-a5dc-e3b9643a9b63" --request PUT --data "failure" https://api.memstash.io/values/DB_MIGRATION_${CIRCLE_WORKFLOW_ID:0:7}
+#             fi
+#             echo "WorkflowID=${CIRCLE_WORKFLOW_ID:0:7}"
+#       - destroy_environment:
+#           id: ${CIRCLE_WORKFLOW_ID:0:7}
+#           when: on_fail
 
-  run-migrations:
-    docker:
-      # Docker image here that supports NodeJS
-    steps:
-      # Checkout code from git
-      - run:
-          name: Run migrations
-          command: |
-            # Your code here
-            exit 1
-      - run:
-          name: Send migration results to memstash
-          command: |
-            # Your code here
-            exit 1
-     # Here's where you will add some code to rollback on failure      
-
-  deploy-frontend:
-    docker:
-      # Docker image here that supports AWS CLI
-    steps:
-      # Checkout code from git
-      - run:
-          name: Install dependencies
-          command: |
-            # your code here
-      - run:
-          name: Get backend url
-          command: |
-            # your code here
-            export API_URL="http://${BACKEND_IP}:3030"
-            echo "${API_URL}"
-      - run:
-          name: Deploy frontend objects
-          command: |
-            # your code here
-      # Here's where you will add some code to rollback on failure      
+#   deploy-frontend:
+#     docker:
+#       - image: circleci/node:13.8.0
+#     steps:
+#       # Checkout code from git
+#       - run:
+#           name: Install AWS CLI dependencies
+#           working_directory: /tmp
+#           command: |
+#             sudo apt-get update && sudo apt-get install -yy less
+#             curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
+#             unzip awscliv2.zip
+#             sudo ./aws/install
+#       - run:
+#           name: Get backend url
+#           command: |
+#             # your code here
+#             export API_URL="http://${BACKEND_IP}:3030"
+#             echo "${API_URL}"
+#       - run:
+#           name: Deploy frontend objects to S3
+#           working_directory: ./frontend
+#           command: |
+#             aws s3 cp ./dist "s3://udapeople-${CIRCLE_WORKFLOW_ID:0:7}" --recursive
+#       - destroy_environment:
+#           id: ${CIRCLE_WORKFLOW_ID:0:7}
+#           when: on_fail
                     
-  deploy-backend:
-    docker:
-      # Docker image here that supports Ansible
-    steps:
-      # Checkout code from git
-      # Add ssh keys with fingerprint
-      # attach workspace
-      - run:
-          name: Install dependencies
-          command: |
-            # your code here
-      - run:
-          name: Deploy backend
-          command: |
-            # your code here
-      # Here's where you will add some code to rollback on failure  
+#   deploy-backend:
+#     docker:
+#       - image: python:3.9.0-alpine
+#     steps:
+#       - checkout
+#       - add_ssh_keys:
+#           fingerprints: ["06:55:19:5c:75:9c:0c:fa:5e:f0:ed:c4:2b:35:ec:76"]
+#       - attach_workspace:
+#           at: .
+#       - run:
+#           name: Install dependencies
+#           working_directory: /tmp
+#           command: |
+#             apk add --update ansible curl rsync openssh nodejs npm
+#             ansible --version
+#             pip install awscli
+#             aws --version
+#       - run:
+#           name: Deploy backend
+#           working_directory: ./.circleci/ansible
+#           command: |
+#             cat inventory
+#             ansible-playbook -i inventory deploy-server.yaml -vv
+#       - destroy_environment:
+#           id: ${CIRCLE_WORKFLOW_ID:0:7}
+#           when: on_fail
 
-  smoke-test:
-    docker:
-      # Lightweight Docker image 
-    steps:
-      # Checkout code from git
-      - run:
-          name: Install dependencies
-          command: |
-            # your code here
-      - run:
-          name: Get backend url
-          command: |
-            # your code here
-      - run:
-          name: Backend smoke test.
-          command: |
-            # your code here
-      - run:
-          name: Frontend smoke test.
-          command: |
-            # your code here
-      # Here's where you will add some code to rollback on failure  
+#   smoke-test:
+#     docker:
+#       - image: alpine:latest
+#     steps:
+#       - checkout
+#       - run:
+#           name: Install dependencies
+#           working_directory: /tmp
+#           command: |
+#             apk add --update curl nodejs npm
+#             pip install awscli
+#       - run:
+#           name: Get backend url
+#           command: |
+#             # your code here
+#       - run:
+#           name: Backend smoke test.
+#           working_directory: ./backend
+#           command: |
+#             export BACKEND_URL=$(curl -H "token: 1e288415-cfc8-4a0a-a23c-087eb7cd7678" --request GET https://api.memstash.io/values/BACKEND_URL)
+#             curl "$BACKEND_URL/api/status"
+#       - run:
+#           name: Frontend smoke test.
+#           working_directory: ./backend
+#           command: |
+#             URL="http://udapeople-${CIRCLE_WORKFLOW_ID:0:7}.s3-website.eu-central-1.amazonaws.com/index.html"
+#             curl -s ${URL} | grep -q "Welcome"
+#       - destroy_environment:
+#           id: ${CIRCLE_WORKFLOW_ID:0:7}
+#           when: on_fail
+#   cloudfront-update:
+#     docker:
+#       - image: amazon/aws-cli
+#     steps:
+#       - checkout
+#       - run:
+#           name: Install dependencies
+#           command: |
+#             yum install -y tar gzip curl
+#             curl -sL https://rpm.nodesource.com/setup_10.x | bash -
+#             yum install -y nodejs
+#       - run:
+#           name: Update cloudfront distribution
+#           working_directory: ./.circleci/files
+#           command: |
+#             aws cloudformation deploy \
+#               --template-file cloudfront.yaml \
+#               --stack-name udapeople-cloudfront-production \
+#               --parameter-overrides WorkflowID="${CIRCLE_WORKFLOW_ID:0:7}" \
+#               --tags project=udapeople  
 
-  cloudfront-update:
-    docker:
-      # Docker image here that supports AWS CLI
-    steps:
-      # Checkout code from git
-      - run:
-          name: Install dependencies
-          command: |
-            # your code here
-      - run:
-          name: Update cloudfront distribution
-          command: |
-            # your code here
-      # Here's where you will add some code to rollback on failure  
-
-cleanup:
-    docker:
-      # Docker image here
-    steps:
-      # Checkout code from git
-      - run:
-          name: Get old stack workflow id
-          command: |
-            # your code here
-            export OldWorkflowID="the id here"
-            export STACKS=[] #put the list of stacks here
-      - run:
-          name: Remove old stacks and files
-          command: |
-            if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
-            then
-              # your code here
-            fi
+# cleanup:
+#     docker:
+#       - image: amazon/aws-cli
+#     steps:
+#       - checkout
+#       - run:
+#           name: Get old stack workflow id
+#           command: |
+#             export OldWorkflowID=$(curl -H "token: 1513db3b-15be-4750-bae6-3a8d32dd6de2" --request GET https://api.memstash.io/values/WorkflowID)
+#             CurrentWorkflowID=${CIRCLE_WORKFLOW_ID:0:7}
+#             export OldWorkflowID="the id here"
+#             export STACKS=[${CIRCLE_WORKFLOW_ID:0:7}]
+#       - run:
+#           name: Remove old stacks and files
+#           command: |
+#             if [[ "${STACKS[@]}" =~ "${OldWorkflowID}" ]]
+#             then
+#               echo "$OldWorkflowID!=$CurrentWorkflowID => will delete old version"
+#               aws s3 rm "s3://udapeople-${OldWorkflowID}" --recursive
+#               aws cloudformation delete-stack --stack-name "udapeople-frontend-${OldWorkflowID}"
+#               aws cloudformation delete-stack --stack-name "udapeople-backend-${OldWorkflowID}"
+#             fi
             
 
 workflows:
@@ -268,30 +366,30 @@ workflows:
     jobs:
       - build-frontend
       - build-backend
-      - test-frontend:
-          requires: [build-frontend]
-      - test-backend:
-          requires: [build-backend]
-      - scan-backend:
-          requires: [build-backend]
-      - scan-frontend:
-          requires: [build-frontend]
-      - deploy-infrastructure:
-          requires: [test-frontend, test-backend, scan-frontend, scan-backend]
-          filters:
-            branches:
-              only: [test-feature-branch]
-      - configure-infrastructure:
-          requires: [deploy-infrastructure]
-      - run-migrations:
-          requires: [configure-infrastructure]
-      - deploy-frontend:
-          requires: [run-migrations]
-      - deploy-backend:
-          requires: [run-migrations]
-      - smoke-test:
-          requires: [deploy-backend, deploy-frontend]
-      - cloudfront-update:
-          requires: [smoke-test]
-      - cleanup:
-          requires: [cloudfront-update]
+      # - test-frontend:
+      #     requires: [build-frontend]
+      # - test-backend:
+      #     requires: [build-backend]
+      # - scan-backend:
+      #     requires: [build-backend]
+      # - scan-frontend:
+      #     requires: [build-frontend]
+      # - deploy-infrastructure:
+      #     requires: [test-frontend, test-backend, scan-frontend, scan-backend]
+      #     filters:
+      #       branches:
+      #         only: [test-feature-branch]
+      # - configure-infrastructure:
+      #     requires: [deploy-infrastructure]
+      # - run-migrations:
+      #     requires: [configure-infrastructure]
+      # - deploy-frontend:
+      #     requires: [run-migrations]
+      # - deploy-backend:
+      #     requires: [run-migrations]
+      # - smoke-test:
+      #     requires: [deploy-backend, deploy-frontend]
+      # - cloudfront-update:
+      #     requires: [smoke-test]
+      # - cleanup:
+      #     requires: [cloudfront-update]
